### ISSUE TITLE
403 Status

### ISSUE THREAD

**Issue by iamluca** [fent/node-miniget#14]
```

Error: Status code: 403
    at ClientRequest.httpLib.get (/hypercast/node_modules/miniget/lib/index.js:123:19)
    at Object.onceWrapper (events.js:324:30)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:550:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:439:20)
    at emitOne (events.js:125:13)
    at TLSSocket.emit (events.js:221:7)
    at addChunk (_stream_readable.js:265:12)
```

**Comment by fent** [comment]
??

**Comment by iamluca** [comment]
I keep getting this random error not sure why.

**Comment by fent** [comment]
403 is considered an errornous status code. Look at the request that's responding with it.

**Comment by iamluca** [comment]
Something with ffmpeg or ytdl-core

**Comment by fent** [comment]
This error is from a request response. It's not related to this library, it's related to the request made with this library.

https://en.wikipedia.org/wiki/HTTP_403
