### ISSUE TITLE
Randomly get this

### ISSUE THREAD

**Issue by DiscordDonut** [fent/node-miniget#2]
```
Error: Status code: 403
    at ClientRequest.<anonymous> (/root/node_modules/miniget/lib/index.js:65:17)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at TLSSocket.Readable.push (_stream_readable.js:211:10)
    at TLSWrap.onread (net.js:585:20)
```

This gets a return then crashes my application while just playing music. Nothing triggered this to happened, this just happens randomly

**Comment by fent** [comment]
Do you have a url where this happens consistently?

**Comment by DiscordDonut** [comment]
I have been running some debug tests, unable to find anywhere where I can
catch where this error occurs since this is just happening out of the blue
of which doesnt make sense. Since I am using the miniget module as a part
of the ytdl-core module, the core part of my Discord bot, I think it might
be something to do with when a new song is trying to be fetched from
youtube. If you could tell me how I can catch this error, I will be more
than happen to add this to my code and provide any errors

**Comment by fent** [comment]
If this happens primarily in ytdl-core, this issue is more related to how ytdl-core makes the request, not this module.

You can catch the error by adding an `error` listener to the stream that `ytdl()` returns.

```js
let stream  = ytdl(url);
stream.on('error', (err) => {
  // do something with `err`
});
```

**Comment by fent** [comment]
Going to close this, feel free to open the issue on the ytdl-core repo with more information so I can help debug.
