### ISSUE TITLE
Status code: 429 when i try to start music Discord.js

### ISSUE THREAD

**Issue by LeManock** [fent/node-miniget#47]
_**The error logs:**_ 

```
Status code: 429
     at ClientRequest.<anonymous> (/app/node_modules/miniget/dist/index.js:141:31)
   at Object.onceWrapper (events.js:422:26)
   at ClientRequest.emit (events.js:315:20)
  at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
   at addChunk (_stream_readable.js:295:12)
at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
 Error: Status code: 429
     at ClientRequest.<anonymous> (/app/node_modules/miniget/dist/index.js:141:31)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
   at TLSSocket.socketOnData (_http_client.js:469:22)
     at TLSSocket.emit (events.js:315:20)
  at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
```

**When I try to start the music, this error appears and when I restart my vps, this problem disappears for 10 to 40 minutes and reappears**

**Comment by MGPlayzYT** [comment]
This is caused by YouTube rate limiting your IP. It's normal and the error usually goes away within 24 hours. If it does not, you need to use proxies or something like that.
