### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by Luke-lwz** [fent/node-miniget#61]
Hi, I'm new to coding and I can't find any solutions to this error: 
`MinigetError: input stream: Status code: 404
    at ClientRequest.<anonymous> (C:\Users\parot\Documents\Projects\DiscordBots\D-Radio-Folder\D-Radio\node_modules\miniget\dist\index.js:211:27)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9) {
  statusCode: 404
}`

Here is my code:
`const stream = await ytdl(playlist[index].shortUrl, {
                filter: "audioonly",
                bitrate: 192000,
                opusEncoded: true,
                encoderArgs: ['-af', 'bass=g=10,dynaudnorm=f=200'],
                quality: "highestaudio"
            });`

working on a discord bot btw.
Hope you can help me

**Comment by PasinduDushan** [comment]
I'm getting that error too

**Comment by redbrain** [comment]
This is an issue with ytdl, and has already been filed at fent/node-ytdl-core#939.
I'd recommend closing this issue since it's a duplicate.

**Comment by Luke-lwz** [comment]
Alright thanks
